customhost = "database-1.czprvzv1bj80.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "wangtengzheng-employee"
customregion = "us-east-1"
